server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    cascade: delete
  datasource:
#    url: jdbc:oracle:thin:@115.28.64.224:1521:sanjiDB
    #url: jdbc:oracle:thin:@192.168.2.247:1522:xe
    url:  jdbc:mysql://localhost:3306/test5?characterEncoding=utf8 
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

logging:
  #日志级别(TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
   level: INFO
  #日志文件 日志文件每达到10M就会被轮换（分割），默认记录ERROR, WARN和INFO级别的信息。
   file: ./demo.log
    
    
